# on: 
#   push:
#   pull_request:

# jobs:
#   echo:
#     runs-on: ubuntu-latest
#     steps: 
#       - run: |
#           echo '1' $GITHUB_REF
#           echo '2' ${{ github.ref }}
#           echo '3' ${{ github.ref_name }}
#           echo '4' ${{ github.head_ref }}
#           echo '5' ${{ github.base_ref }}
#           echo '6' ${{ github.event.head_commit.message }}
#           echo '7' ${{ github.event.sender.avatar_url }}
#           echo '7' ${{ github.actor }}
#           echo '7' ${{ env.COMMIT_MESSAGE  }}
# name: Create a pull request for release.

on:
  push:
    # branches: [ develop ]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    # GithubTokenを使ってPRを立てる
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      # リリース用PRが既に存在するかどうかをチェック
      - name: Check if pr exists
        id: check_pr
        run: |
          echo "::set-output name=count::$(gh pr list -S ${pr_title}' in:本番反映' | wc -l)"
          echo "::set-output name=base_branch::$base_branch"
      # リリース用PRを作成
      - name: Create release pr
        if: ${{ steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create \
            -B main \
            -t '【本番反映】${{ github.event.head_commit.message }}' \
            -b "# 本番反映\nここに文字列" \
            -a ${{ github.actor }} 
      - name: Edit release pr
        if: ${{ steps.check_pr.outputs.count != 0 }}
        run: |
          PRITEM=$(gh pr list -S ${pr_title}' in:本番反映' \
            --json "number,title,body" \
            | jq -c .[])
          echo PR_NUMBER
          # echo prJson | jq .
          # gh pr edit \
          #   -B main \
          #   -t '【本番反映】${{ github.event.head_commit.message }}' \
          #   -b "# 本番反映\nここに文字列" \
          #   -a ${{ github.actor }} 
