on: 
  push:
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
          echo '6' ${{ github.event.head_commit.message }}
          echo '7' ${{ github.event.sender.avatar_url }}
          echo '7' ${{ github.actor }}
          echo '7' ${{ env.COMMIT_MESSAGE  }}
